sonar.projectKey=Siddheshwarkhilari_Ganesh
sonar.organization=siddheshwarkhilari

sonar.projectName=KaveriGSAutoMech
sonar.projectVersion=1.0

# source folders
sonar.sources=.

# exclude the build artifacts and node_modules
sonar.exclusions=node_modules/**,dist/**,build/**

# Optional – for TypeScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info
